use 20200128db;

#Query 1
SELECT A.CUST_NAME AS 'CUSTOMER NAME'
FROM CUSTOMER A 
INNER JOIN SALESMAN B 
ON A.SALESMAN_ID=B.SALESMAN_ID;

#Query 2
SELECT A.CUST_NAME AS 'CUSTOMER NAME', 
A.CITY, B.NAME AS 'SALESMAN', B.COMMISSION 
FROM CUSTOMER A 
INNER JOIN SALESMAN B 
ON A.SALESMAN_ID=B.SALESMAN_ID 
WHERE B.COMMISSION>.12;

#Query 3
SELECT A.CUST_NAME AS 'CUSTOMER NAME', 
A.CITY, B.NAME AS 'SALESMAN', B.CITY,B.COMMISSION  
FROM CUSTOMER A  
INNER JOIN SALESMAN B  
ON A.SALESMAN_ID=B.SALESMAN_ID 
WHERE B.COMMISSION>.12 
AND A.CITY<>B.CITY;

#Query 4
SELECT * 
FROM ORDERS 
NATURAL JOIN CUSTOMER  
NATURAL JOIN SALESMAN;

#Query 5
SELECT A.CUST_NAME,A.CITY,A.GRADE, 
B.NAME AS 'SALESMAN',B.CITY 
FROM CUSTOMER A 
LEFT JOIN SALESMAN B 
ON A.SALESMAN_ID=B.SALESMAN_ID 
ORDER BY A.CUSTOMER_ID;

#Query 6
SELECT * 
FROM SALESMAN A 
CROSS JOIN CUSTOMER B;

#Creating course and pre-requisite
CREATE TABLE COURSE2
(
COURSE_ID VARCHAR(10),
TITLE varchar(20),
DEPT_NAME varchar(20),
CREDITS int(2),
primary key (COURSE_ID)
);

CREATE TABLE PREREQ2
(
COURSE_ID VARCHAR(10),
PREREQ_ID varchar(20)
);

#Insering the values
INSERT INTO COURSE2 VALUES('BIO-301','Genetics','Biology',4);
INSERT INTO COURSE2 VALUES('CS-190','Game Design','Comp. Sci.',4);
INSERT INTO COURSE2 VALUES('CS-315','Robotics','Comp. Sci.',3);

INSERT INTO PREREQ2 VALUES('BIO-301','BIO-101');
INSERT INTO PREREQ2 VALUES('CS-190','CS-101');
INSERT INTO PREREQ2 VALUES('CS-347','CS-101');

#Query 7
SELECT * FROM COURSE2
LEFT OUTER JOIN PREREQ2
ON COURSE2.COURSE_ID = PREREQ2.COURSE_ID;

#Query 8
SELECT * FROM COURSE2
RIGHT OUTER JOIN PREREQ2
ON COURSE2.COURSE_ID = PREREQ2.COURSE_ID;

#Query 9
SELECT * FROM COURSE2
LEFT OUTER JOIN PREREQ2
ON COURSE2.COURSE_ID = PREREQ2.COURSE_ID
UNION
SELECT * FROM COURSE2 
RIGHT OUTER JOIN PREREQ2
ON COURSE2.COURSE_ID = PREREQ2.COURSE_ID;
