use 20200128db;

#Query 1
SELECT *
FROM SALESMAN 	
WHERE CITY=ANY
    (SELECT CITY
     FROM CUSTOMER);
     
#Query 2
SELECT *
FROM ORDERS
WHERE PURCH_AMT > ANY
   (SELECT PURCH_AMT
	FROM ORDERS
	WHERE  ORD_DATE='2012-09-10');
    
#Query 3
SELECT *
FROM ORDERS
WHERE PURCH_AMT < 
   (SELECT MAX(PURCH_AMT)
	FROM ORDERS A, CUSTOMER B
	WHERE  A.CUSTOMER_ID=B.CUSTOMER_ID
	AND B.CITY='LONDON');
    
#Query 4
SELECT *
FROM CUSTOMER
WHERE GRADE > ALL
   (SELECT GRADE
	FROM CUSTOMER
	WHERE CITY='NEW YORK');

#Query 5
SELECT * FROM CUSTOMER WHERE GRADE <> ALL 
(SELECT GRADE FROM CUSTOMER WHERE CITY='LONDON' AND NOT GRADE IS NULL);

#Query 6
SELECT *
FROM ORDERS
WHERE SALESMAN_ID =
    (SELECT SALESMAN_ID 
     FROM SALESMAN 
     WHERE NAME='PAUL ADAM');
     
#Query 7
SELECT *
FROM ORDERS
WHERE SALESMAN_ID IN
    (SELECT SALESMAN_ID 
     FROM SALESMAN 
     WHERE CITY='LONDON');
     
#Query 8
SELECT *
FROM ORDERS
WHERE PURCH_AMT >
    (SELECT  AVG(PURCH_AMT) 
     FROM ORDERS 
     WHERE ORD_DATE ='2012-10-10');
     
#Query 9
SELECT COMMISSION
FROM SALESMAN
WHERE SALESMAN_ID IN
    (SELECT SALESMAN_ID 
     FROM CUSTOMER
     WHERE CITY = 'PARIS');
     
#Query 10
SELECT *
FROM CUSTOMER 
WHERE CUSTOMER_ID IN 
(SELECT CUSTOMER_ID FROM ORDERS WHERE ORD_DATE = '2012-10-05');

